version: '2'

services:
  proxy:
    image: drakerin/rpi-alpine-nginx:latest
    container_name: "portainer-proxy"
    ports:
      - "80:80"
    networks:
      - local
    volumes_from:
      - container:portainer-password

  portainer:
    image: portainer/portainer:arm
    container_name: "portainer-app"
    command: -d /data --swarm
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    image: armhfbuild/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
